services:
  # Servicio DynDNS
  dyndns:
    build:
      context: ./scripts/dyndns
    container_name: dyndns
    networks:
      - default

  # Servicio Nginx
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile 
    container_name: nginx
    ports:
      - 8080:80
      - 8443:443
      - 1935:1935
    depends_on:
      - dyndns
    networks:
      - default

  # Servicio PHP
  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    networks:
      - default

networks:
  default:
    driver: bridge
