services:
  # Servicio DynDNS
  dyndns:
    build:
      context: scripts/dyndns
    container_name: dyndns
    networks:
      - default

  # Servicio Nginx
  nginx:
    build:
      context: .
      dockerfile: src/nginx/docker/Dockerfile 
    container_name: nginx
    ports:
      - 8080:80
      - 8443:443
      - 1935:1935
    depends_on:
      - dyndns
    volumes:
      - ./src/nginx/webpages/videos/hls:/var/www/webpages/videos/hls
    networks:
      - default

  # Servicio PHP
  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    networks:
      - default

  icecast:
    image: libretime/icecast
    container_name: icecast
    ports:
      - "8000:8000"
    volumes:
      - ./config/icecast/icecast.xml:/etc/icecast.xml
    environment:
      - ICECAST_SOURCE_PASSWORD=sourcepass
      - ICECAST_ADMIN_PASSWORD=hackme
      - ICECAST_PASSWORD=hackme
      - ICECAST_HOSTNAME=icecast
    networks:
      - default

  ices2:
    build:
      context: .
      dockerfile: icecast/ices2/Dockerfile 
    container_name: ices2
    depends_on:
      - icecast
    volumes:
      - ./config/icecast/ices2/ices-playlist.xml:/etc/ices2/ices-playlist.xml
      - ./config/icecast/mymusic:/songs
    networks:
      - default

  telegram:
    build:
      context: .
      dockerfile: telegramBot/docker/Dockerfile
    container_name: telegram
    volumes:
      - ./src/nginx/webpages/videos/hls:/videos
      - ./config/icecast/mymusic:/songs
    networks:
      - default

networks:
  default:
    driver: bridge
